### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by kuangshp** [xx19941215/light-go#1]
我是建议作者从最开始的环境的安装及编辑器的选择开始,对于我们没接触过go语言的人来说很有必要

**Comment by xx19941215** [comment]
@kuangshp 好的 稍后这块补上  谢谢您的建议

**Comment by xx19941215** [comment]
[Go环境安装](https://github.com/xx19941215/light-go/blob/master/c01/c01_1/start.md) 已补上 @kuangshp
